"""parent child vendor hierarchy

Revision ID: 35b275d81a1f
Revises: 28a4ebae163d
Create Date: 2026-05-20 12:34:35.507504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b275d81a1f'
down_revision: Union[str, Sequence[str], None] = '28a4ebae163d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_foreign_key(None, 'pricing_models', 'vendors', ['vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'recommendation_metadata', 'vendors', ['vendor_id'], ['vendor_id'])
    op.alter_column('reviews', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.create_foreign_key(None, 'reviews', 'vendors', ['vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'semantic_embeddings', 'vendors', ['vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'user_preferences', 'vendors', ['favorite_vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'user_preferences', 'categories', ['preferred_category_id'], ['category_id'])
    op.create_foreign_key(None, 'user_preferences', 'subcategories', ['preferred_subcategory_id'], ['subcategory_id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'vendor_media', 'vendors', ['vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'vendor_services', 'vendors', ['vendor_id'], ['vendor_id'])
    op.add_column('vendors', sa.Column('parent_vendor_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vendors', 'vendors', ['parent_vendor_id'], ['vendor_id'])
    op.create_foreign_key(None, 'viewed_vendors', 'vendors', ['vendor_id'], ['vendor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'viewed_vendors', type_='foreignkey')
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'parent_vendor_id')
    op.drop_constraint(None, 'vendor_services', type_='foreignkey')
    op.drop_constraint(None, 'vendor_media', type_='foreignkey')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.drop_constraint(None, 'user_preferences', type_='foreignkey')
    op.drop_constraint(None, 'semantic_embeddings', type_='foreignkey')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.alter_column('reviews', 'is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint(None, 'recommendation_metadata', type_='foreignkey')
    op.drop_constraint(None, 'pricing_models', type_='foreignkey')
    op.alter_column('conversations', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
